# =========================================================
#                Webserv42 - Configuration file
# =========================================================
# Ce fichier définit plusieurs serveurs et locations
# au format inspiré de Nginx.
# =========================================================


# ----------------------------
# Serveur principal (localhost)
# ----------------------------
server {
    listen 8080;
    server_name localhost;

    root www;
    index index.html;
    client_max_body_size 2M;

    # --- Page d'accueil / fichiers statiques
    location / {
        root www;
        index index.html;
        autoindex off;
    }

    # --- Répertoire d’upload
    location /upload {
        root www/upload;
        upload_path www/upload/;
        autoindex on;
        allow_methods GET POST DELETE;
    }

    # --- CGI Python
    location /cgi-bin {
        root www/cgi-bin;
        cgi .py /usr/bin/python3;
        allow_methods GET POST;
    }

    # --- Redirection /oldpage → /newpage
    location /oldpage {
        return 301 /newpage;
    }
}


# --------------------------------------
# Second serveur virtuel sur un autre port
# --------------------------------------
server {
    listen 8081;
    server_name test.local;

    root www/test_site;
    index index.html;

    location / {
        root www/test_site;
        autoindex on;
    }
}
