#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<html><head><title>Server Info CGI</title></head>"
echo "<body style='font-family: Arial; padding: 20px;'>"
echo "<h1>Server Information (Shell CGI)</h1>"
echo "<h2>Environment Variables:</h2>"
echo "<ul>"
echo "<li><b>REQUEST_METHOD:</b> $REQUEST_METHOD</li>"
echo "<li><b>QUERY_STRING:</b> $QUERY_STRING</li>"
echo "<li><b>SERVER_NAME:</b> $SERVER_NAME</li>"
echo "<li><b>SERVER_PORT:</b> $SERVER_PORT</li>"
echo "<li><b>SCRIPT_NAME:</b> $SCRIPT_NAME</li>"
echo "<li><b>PATH_INFO:</b> $PATH_INFO</li>"
echo "</ul>"
echo "<h2>System Info:</h2>"
echo "<ul>"
echo "<li><b>Date:</b> $(date)</li>"
echo "<li><b>Uptime:</b> $(uptime)</li>"
echo "<li><b>User:</b> $(whoami)</li>"
echo "</ul>"
echo "</body></html>"
